// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-ajFgh5nNBX5Ep58GC_9bGg8VPQ05vM4',
    appId: '1:1011820326368:web:d022b0e34482319d798f85',
    messagingSenderId: '1011820326368',
    projectId: 'quimisol-4f159',
    authDomain: 'quimisol-4f159.firebaseapp.com',
    databaseURL: 'https://quimisol-4f159-default-rtdb.firebaseio.com',
    storageBucket: 'quimisol-4f159.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPhA_MJbwQYqjNhcrcQWbJvJ4gPTplBgQ',
    appId: '1:1011820326368:android:a78abf2cae4575d3798f85',
    messagingSenderId: '1011820326368',
    projectId: 'quimisol-4f159',
    databaseURL: 'https://quimisol-4f159-default-rtdb.firebaseio.com',
    storageBucket: 'quimisol-4f159.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK-IeSH17z4N4VztxhifghxE4TQiiboSQ',
    appId: '1:1011820326368:ios:82fad930a1fd97c6798f85',
    messagingSenderId: '1011820326368',
    projectId: 'quimisol-4f159',
    databaseURL: 'https://quimisol-4f159-default-rtdb.firebaseio.com',
    storageBucket: 'quimisol-4f159.firebasestorage.app',
    androidClientId: '1011820326368-ie96ej2gh4spv0ra9gl4up7mj5odi974.apps.googleusercontent.com',
    iosClientId: '1011820326368-ad2q0c0uai5irfkkrloveovdakh2ssn0.apps.googleusercontent.com',
    iosBundleId: 'com.example.quimisolWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK-IeSH17z4N4VztxhifghxE4TQiiboSQ',
    appId: '1:1011820326368:ios:82fad930a1fd97c6798f85',
    messagingSenderId: '1011820326368',
    projectId: 'quimisol-4f159',
    databaseURL: 'https://quimisol-4f159-default-rtdb.firebaseio.com',
    storageBucket: 'quimisol-4f159.firebasestorage.app',
    androidClientId: '1011820326368-ie96ej2gh4spv0ra9gl4up7mj5odi974.apps.googleusercontent.com',
    iosClientId: '1011820326368-ad2q0c0uai5irfkkrloveovdakh2ssn0.apps.googleusercontent.com',
    iosBundleId: 'com.example.quimisolWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-ajFgh5nNBX5Ep58GC_9bGg8VPQ05vM4',
    appId: '1:1011820326368:web:ef317879c81fa3cc798f85',
    messagingSenderId: '1011820326368',
    projectId: 'quimisol-4f159',
    authDomain: 'quimisol-4f159.firebaseapp.com',
    databaseURL: 'https://quimisol-4f159-default-rtdb.firebaseio.com',
    storageBucket: 'quimisol-4f159.firebasestorage.app',
  );
}
